config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name="home"),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name="about"),

    # Django Admin, use {% url 'admin:index' %}
    url(r'^grappelli/', include('grappelli.urls')), # grappelli URLS
    url(settings.ADMIN_URL, include(admin.site.urls)),

    # User management
    url(r'^users/', include("jaguares.users.urls", namespace="users")),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^proyecto/', include("proyecto.urls", namespace="proyecto")),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception("Bad Request!")}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception("Permissin Denied")}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception("Page not Found")}),
        url(r'^500/$', default_views.server_error),
    ]

jaguares/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

proyecto/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

app_name = 'proyecto'
urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.ProyectoListView.as_view(),
        name='list'
    ),

    url(
        regex=r'^(?P<nombre>[\w.@+-]+)/$',
        view=views.ProyectoDetailView.as_view(),
        name='detail'
    ),

    url(
        regex=r'^(?P<nombre>[\w.@+-]+)/kanban/(?P<sprintId>[0-9]+)$',
        view=views.kanban,
        name='kanban'
    ),
    url(
        regex=r'^(?P<nombre>[\w.@+-]+)/tablero/(?P<sprintId>[0-9]+)$',
        view=views.tablero,
        name='tablero'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.ProyectoUpdateView.as_view(),
        name='update'
    ),
]

jaguares/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_("Nombre de Usuario"), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

proyecto/models.py
from __future__ import unicode_literals
from django.db                  import models
from django.conf                import settings
from django.utils.translation   import ugettext_lazy as _
from django.core.validators     import RegexValidator
from datetime                   import datetime
from polymorphic.models         import PolymorphicModel

class Comentario(PolymorphicModel):
    
    def resumen(self):
        return self.comentario[:120]
    
    comentario = models.TextField()
    fecha = models.DateTimeField(_(u'Fecha del comentario'),
                                default=datetime.now(), 
                                editable=False)

    def __str__(self):
        return self.resumen()


class Rol(models.Model):
    nombre = models.CharField(max_length=30)
    descripción = models.TextField()

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name_plural= _(u'Roles')


class EstadoEmocional(models.Model):
    nombre = models.CharField(_(u'Estado Emocional'), max_length=30, default='')
    descripción = models.CharField(_(u'descripción'), max_length=250, default='')

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name_plural = _(u'Estados Emocionales')


class Estado(models.Model):
    nombre = models.CharField(_(u'Estado'), max_length=30, default='')
    descripción = models.CharField(_(u'descripción'), max_length=250, default='')

    def __str__(self):
        return self.nombre


class Prioridad(models.Model):
    nombre = models.CharField(_(u'Estado'), max_length=30, default='')
    descripción = models.CharField(_(u'descripción'), max_length=250, default='')
    valor = models.IntegerField(default = 0)
    
    def __str__(self):
        return self.nombre
    
    class Meta:
        verbose_name_plural = _(u'Prioridades')


class Proyecto(models.Model):
    nombre = models.CharField(_(u'Proyecto'), max_length=250, unique=True)
    descripción = models.CharField(_(u'Descripción'), max_length=250)
    creado = models.DateTimeField(default=datetime.now(), editable=False)
    fechaInicio = models.DateTimeField(_(u'Fecha inicio'), default=datetime.now(), editable=True)
    duración = models.DurationField(_(u'Duración (Dias hh:mm:ss)'))

    def __str__(self):
        return self.nombre


class ComentarioProyecto(Comentario):
    proyecto = models.ForeignKey(Proyecto)


class Miembro(models.Model):
    rol = models.ForeignKey(Rol)
    persona = models.ForeignKey(settings.AUTH_USER_MODEL)
    proyecto = models.ForeignKey(Proyecto)

    def __str__(self):
        return self.persona.get_username() + " (" + self.rol.nombre + ") Proy:" + self.proyecto.nombre


class Documento(PolymorphicModel):
    nombre =      models.CharField(_(u'Nombre'), max_length=250)
    descripción = models.CharField(_(u'Descripción'), max_length=250)
    creado =      models.DateTimeField(auto_now=True, editable=False)
    archivo =     models.FileField(upload_to=u'Documentos')
    dueño =       models.ForeignKey(Miembro)

    def __str__(self):
        return self.nombre


class Sprint(models.Model):
    nombre = models.CharField(_(u'Nombre'), max_length=250)
    proyecto = models.ForeignKey(Proyecto)
    descripción = models.TextField(_(u'descripción'), default='')
    inicio = models.DateTimeField(default=datetime.now())
    fin = models.DateTimeField(default=datetime.now())
    finalizado = models.BooleanField(default=False)

    def _get_duración(self):
        return (self.fin - self.inicio).days

    duración = property(_get_duración)
    adjunto = models.ForeignKey(Documento, null=True, blank=True)

    def __str__(self):
        return ('Sprint '+ self.nombre) 


class ComentarioSprint(Comentario):
    sprint = models.ForeignKey(Sprint)
    def __str__(self):
        return self.sprint.nombre


class DocumentoSprint(Documento):
    sprintRef = models.ForeignKey(Sprint)


class DocumentoProyecto(Documento):
    proyecto = models.ForeignKey(Proyecto)

    class Meta:
        verbose_name_plural = _(u'Documentos adjuntos Proyecto')


class HistoriaUsuario(models.Model):
    numeroHistoria = models.IntegerField(_(u'Nro. Historia'), default=0, editable=False)
    fechaElaboracion = models.DateTimeField(_(u'Fecha elaboración'), default=datetime.now(),editable=False)
    personaElaboro = models.CharField(_(u'Elaborado por'), max_length=200,default='', editable=False)
    titulo = models.TextField(_(u'Titulo'), default='')
    descripción = models.TextField(_(u'descripción'), default='')
    prioridad = models.ForeignKey(Prioridad, null=True, blank=True)
    tiempoEstimado = models.DecimalField(_(u'Tiempo estimado'), default=0,max_digits=10,decimal_places=2)
    persona = models.ForeignKey(settings.AUTH_USER_MODEL,verbose_name='Responsable', null=True, blank=True)
    proyecto = models.ForeignKey(Proyecto, null=True, blank=True)

    def __str__(self):
        return self.titulo
    
    def estaTerminado(self):
        tareas = self.tarea_set.all() 
        if len(tareas) == 0:
            return False
        for tarea in tareas:
            if tarea.estado.nombre != 'Done':
                return False
        return True
        
    class Meta:
        verbose_name_plural = _(u'Product Backlog')


class DocumentoHistoriaUsuario(Documento):
    historiaUsuario = models.ForeignKey(HistoriaUsuario)


class CriterioAceptacion(models.Model):
    resumen = models.CharField(max_length=30)
    descripción = models.CharField(max_length=250)
    autor = models.ForeignKey(Miembro)
    historiaUsuario = models.ForeignKey(HistoriaUsuario)

    def __str__(self):
        return self.resumen

    class Meta:
          verbose_name_plural = _(u'Criterios de aceptación')


class HistoriaUsuarioSprint(models.Model):
    historiaUsuario = models.ForeignKey(HistoriaUsuario)
    sprint = models.ForeignKey(Sprint, limit_choices_to={'finalizado': False})

    def __str__(self):
        return self.sprint.nombre + " - " + self.historiaUsuario.titulo

    class Meta:
        verbose_name_plural = _(u'Asignacion HU - Sprint')


class Tarea(models.Model):
    titulo = models.CharField(_(u'Nombre'),max_length=200,default='')
    descripción = models.TextField(_(u'descripción'),default='')
    progreso = models.DecimalField('Progreso (de 0 a 100)',default=0,max_digits=10,decimal_places=2)
    documento = models.ForeignKey(Documento,null=True,blank=True)
    miembro = models.ForeignKey(Miembro,null=True,blank=True, verbose_name='Responsable')
    estado = models.ForeignKey(Estado,default=1)
    historiaUs = models.ForeignKey(HistoriaUsuario)

    def __str__(self):
        return self.titulo


class ComentarioTarea(Comentario):
    tarea = models.ForeignKey(Tarea)


class HistoriaTarea(models.Model):
    progreso = models.DecimalField(('Progreso'),max_digits=10,decimal_places=2)
    fecha = models.DateTimeField(('Fecha'),default=datetime.now(),editable=False)
    comentarios = models.TextField(default='')
    tarea = models.ForeignKey(Tarea)

    def __str__(self):
        return self.tarea.titulo + self.progreso

    class Meta:
        verbose_name_plural = _(u'Historia de las Tareas')

jaguares/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from braces.views import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"

proyecto/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView
from braces.views import LoginRequiredMixin
from .models import Proyecto, Sprint, HistoriaUsuario, Estado, Tarea, HistoriaUsuarioSprint, Miembro

def kanban(request, nombre, sprintId):
    p = Proyecto.objects.get(nombre=nombre)
    s = Sprint.objects.filter(proyecto=p.pk)
    sprint = Sprint.objects.get(pk=sprintId);
    historiasUsuariosSprint = sprint.historiausuariosprint_set.all();
    hu = HistoriaUsuario.objects.filter(proyecto=p.pk)
    for h in hu:
        h.tareas = Tarea.objects.filter(historiaUs = h.pk)
    es = Estado.objects.all()
    return render(request, 'proyecto/proyecto_kanban.html', 
                 {
                     'proyecto':p, 
                     'sprints':s, 
                     'historiasU':hu,
                     'estados':es, 
                     'historiasUsuariosSprint' : historiasUsuariosSprint, 
                     'sprint' : sprint
                })
def tablero(request, nombre, sprintId):
    proyecto = Proyecto.objects.get(nombre=nombre)
    sprint = Sprint.objects.get(pk=sprintId)
    estados = Estado.objects.all()
    test = 'get';
    if request.method == 'POST':
        if request.POST.get('action') == 'tarea_crear':
           hu_id = request.POST.get('hu_id')
           tarea_nombre = request.POST.get('tarea_nombre')
           tarea_descripcion = request.POST.get('tarea_descripcion')
           historia = HistoriaUsuario.objects.get(pk=hu_id)
           tarea = Tarea.objects.create(titulo=tarea_nombre, descripción=tarea_descripcion, historiaUs=historia)
           tarea.save()
        else:  
            tarea = request.POST.get('tarea_id')
            titulo = request.POST.get('tarea_nombre')
            descripcion = request.POST.get('tarea_descripcion')
            responsable = request.POST.get('tarea_miembro')
            estado = request.POST.get('tarea_estado')
            if responsable == "0":
                responsable = None
            else:             
                responsable = Miembro.objects.get(pk=responsable)
            tarea = Tarea.objects.get(pk=tarea)
            tarea.estado = Estado.objects.get(pk=estado)
            tarea.miembro = responsable
            tarea.titulo = titulo
            tarea.descripción = descripcion
            tarea.save()
    
    return render(request, 'proyecto/tablero.html', {
         'proyecto' : proyecto,
         'sprint' : sprint,
         'estados' : estados,
         'test' : test
    })


class ProyectoDetailView(LoginRequiredMixin, DetailView):
    model = Proyecto
    slug_field = 'nombre'
    slug_url_kwarg = 'nombre'


class ProyectoKanbanView(LoginRequiredMixin, DetailView):
    template_name = 'proyecto/proyecto_kanban.html'
    model = Proyecto
    slug_field = 'nombre'
    slug_url_kwarg = 'nombre'


class ProyectoUpdateView(LoginRequiredMixin, UpdateView):
    model = Proyecto


class ProyectoListView(LoginRequiredMixin, ListView):
    model = Proyecto

jaguares/templates/proyecto/.#proyecto_kanban.html
daniel@kumo.6259

jaguares/templates/proyecto/proyecto_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}Proyecto: {{ object.nombre }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.nombre }}</h2>
      {% if object.descripción %}
        <p>{{ object.descripción }}</p>
      {% endif %}
    </div>
  </div>

<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12 ">
    <a class="btn btn-primary" href="{% url 'proyecto:update' %}">Edit...</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->


</div>
{% endblock content %}

jaguares/templates/proyecto/proyecto_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
    <h1>{{ user.username }}</h1>
    <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="control-group">
          <div class="controls">
            <button type="submit" class="btn">Update</button>
          </div>
        </div>
    </form>
{% endblock %}

jaguares/templates/proyecto/proyecto_list.html
{% extends "base.html" %}
{% load static %}{% load i18n %}
{% block title %}Proyectos{% endblock %}

{% block content %}

<div class="container">

    <h2>Proyectos</h2>

    <div class="list-group">
        {% for proyecto in proyecto_list %}
          <a href="{% url 'proyecto:detail' proyecto.nombre %}" class="list-group-item">
            <h4 class="list-group-item-heading">{{ proyecto.nombre }}</h4>
          </a>
        {% endfor %}

    </div>

{% endblock content %}

jaguares/templates/proyecto/tablero.html
{% extends "bootstrap.html" %}
{% load static %}
{% load i18n %}
{% block title %} Tablero Scrum {% endblock %}

{% block contenido %}

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-primary">
            <div class="panel-heading">{{ proyecto.nombre }}</div>
            <div class="panel-body"> {{ proyecto.descripción }} </div>
        </div>
    </div>
    <div class="col-md-12">
        <div class="panel panel-info">
            <div class="panel-heading"><h4>Sprint {{ sprint.nombre }}</h4></div>
            <div class="panel-body">
              <div class="row">
                <div class="col-xs-12 col-md-8">
                <h4>Descripcion: {{ sprint.descripción }}</h4>
                </div>
                <div class="col-xs-6 col-md-4">
                <h4>Inicio: {{ sprint.inicio }}</h4>
                <h4>Fin: {{ sprint.fin }}</h4>
                <h4>Estado del sprint: 
                {% if sprint.finalizado  %}
                    <span class="label label-danger">Finalizado</span>
                {% else  %}
                    <span class="label label-success">En progreso</span>
                {% endif  %}
                </h4>
                </div>
              </div>
            </div>
        </div>
    </div>
</div> 
<div class="row">
    <div class="col-md-3">
        <div class="panel panel-success">
            <div class="panel-heading">Sprint Backlog</div>
            <div class="panel-body">
            {% for hus in sprint.historiausuariosprint_set.all %}
                <div class="alert alert-success" role="alert"> 
                    <strong>{{ hus.historiaUsuario.titulo  }}</strong> 
                    {% if hus.historiaUsuario.estaTerminado %}
                    <span style="float:right" class="label label-success"> TERMINADO </span>
                    {% else %}
                    <span style="float:right" class="label label-warning"> EN PROGRESO </span>
                    {% endif %}
                    <br>
                    {{ hus.historiaUsuario.descripción }} <br>
                    <br>
                    <button type="button" class="btn btn-success btn-sm" data-toggle="collapse" data-target="#historiausuario-crear-{{ hus.historiaUsuario.id }}"> 
                        <span class="glyphicon glyphicon-plus"> </span>
                    </button> 
                    <button type="button" class="btn btn-success btn-sm" data-toggle="collapse" data-target="#historiausuario-mostrar-{{ hus.historiaUsuario.id }}"> 
                        <span class="glyphicon glyphicon-eye-open"> </span>
                    </button> 
                    <div id="historiausuario-mostrar-{{ hus.historiaUsuario.id }}" class="collapse">
                    <h4 class="text-center"><strong>Mas Informacion</strong></h4>
                    Prioridad : {{ hus.historiaUsuario.prioridad  }} <br>
                    Tiempo Estimado : {{ hus.historiaUsuario.tiempoEstimado  }} <br>
                    <h4> Criterios de Aceptacion</h4>
                    <ul class="list-group"> 
                        {% for criterio in hus.historiaUsuario.criterioaceptacion_set.all  %}
                        <li class="list-group-item"> {{ criterio.descripción }}</li>
                        {% endfor %}
                    </ul>
                    </div>
                    <div id="historiausuario-crear-{{ hus.historiaUsuario.id }}" class="collapse">
                                          
                    <h4 class="text-center"><strong> Crear Tarea</strong></h4>
      <form action="" method="post" role="form" data-toggle="validator" novalidate="true" >
      {% csrf_token %} 
      <input type="hidden" name="action" value="tarea_crear">
      <input type="hidden" name="hu_id" value="{{ hus.historiaUsuario.id }}">
      <div class="form-group has-feedback">
          <label for="tarea_nombre" class="control-label"  > Nombre  </label>
          <input class="form-control" type="text" id="tarea_nombre" name="tarea_nombre" required placeholder="Nombre de la tarea">
          <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
      </div>
      <div class="form-group has-feedback">
          <label for="tarea_descripcion" class="control-label"> Descripcion </label>
          <textarea class="form-control" id="tarea_descripcion" name="tarea_descripcion" required placeholder="Descripcion de la Tarea"></textarea>
          <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
      </div>
      <div class="form-group">
          <button type="submit" class="btn btn-success"> OK  </button>
      </div> 

      </form>  


                    </div>  
                </div>
            {% endfor %}    
            </div>
        </div>
    </div>
    {% for estado in estados %}
    <div class="col-md-3">
        <div class="panel panel-info">
            <div class="panel-heading">{{ estado.nombre }}</div>
        <div class="panel panel-body">
            {% for hus in sprint.historiausuariosprint_set.all %} 
                {% for tarea in hus.historiaUsuario.tarea_set.all %}
                    {% if tarea.estado == estado %}
            <div class="alert alert-info">
               <strong>{{ tarea.titulo }} </strong> 
               <span style="float:right" class="label label-primary"> {{ tarea.historiaUs.titulo }} </span>
               <span style="float:right" class="label label-info"> {% if tarea.miembro.persona.username %} {{ tarea.miembro.persona.username }} {% else %} SR{% endif %} </span>
               <p> {{ tarea.descripción }}</p>
<button type="button" class="btn btn-info btn-sm" data-toggle="collapse" data-target="#tarea-edit-{{ tarea.id  }}">
<span class="glyphicon glyphicon-edit">
</button>
  <div id="tarea-edit-{{ tarea.id }}" class="collapse">
      <form action="" method="post" role="form" data-toggle="validator">
      {% csrf_token %} 
      <input type="hidden" name="tarea_id" value="{{ tarea.id }}">
      <div class="form-group has-feedback">
          <label for="tarea_nombre" class="control-label"  > Nombre  </label>
          <input class="form-control" type="text" id="tarea_nombre" value="{{ tarea.titulo }}" name="tarea_nombre" required placeholder="Nombre de la tarea">
          <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
      </div>
      <div class="form-group has-feedback">
          <label for="tarea_descripcion" class="control-label"> Descripcion </label>
          <textarea class="form-control" id="tarea_descripcion" name="tarea_descripcion" required placeholder="Descripcion de la Tarea">{{ tarea.descripción }}</textarea>
          <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
      </div>
      <div class="form-group">
          <label> Estado </label>
          <select class="form-control" name="tarea_estado">
              {% for est in estados  %}
              <option value="{{ est.id }}" {% if est.nombre == estado.nombre  %} selected {% endif  %} >{{ est.nombre  }} </option>
              {% endfor %}
          </select>
      </div>
      <div class="form-group">
          <label> Responsable </label>
          <select class="form-control" name="tarea_miembro">
              <option value="0" > Sin Responsable </option>
              {% for miembro in proyecto.miembro_set.all %}
              <option value="{{ miembro.id }}" {% if tarea.miembro.persona.username == miembro.persona.username %} selected {% endif %} > {{ miembro.persona.username  }} </option>
              {% endfor %}
          </select>
      </div>
      <div class="form-group">
          <button type="submit" class="btn btn-primary"> OK  </button>
      </div>
      </form>  
  </div>
            </div>
                    {% endif %}
                {% endfor %}
            {% endfor  %}            
        </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock  %}